<?php
/*
Template Name: Customer Home Page


*/

get_header();
?>

<div class="banner d-block" style="height: 350px; background-image: url('https://images.pexels.com/photos/3225517/pexels-photo-3225517.jpeg'); background-size: cover; background-position: center;">
    <div class="container d-flex justify-content-center">
        <div class="mask d-flex flex-column justify-content-center text-center">
            <h4 class="text-center">In need of wood?<br>We have a solution!</h4>
        </div>
    </div>
</div>

<div class="vstack gap-3 col-md-8 mx-auto mt-5">
	<h5 class="text-center">List of Locations</h5>	

	<?php
	$taxonomy     = 'product_cat';
	$orderby      = 'name';  
	$show_count   = 0;      // 1 for yes, 0 for no
	$pad_counts   = 0;      // 1 for yes, 0 for no
	$hierarchical = 1;      // 1 for yes, 0 for no  
	$title        = '';  
	$empty        = 0;

	$args = array(
			'taxonomy'     => $taxonomy,
			'orderby'      => $orderby,
			'show_count'   => $show_count,
			'pad_counts'   => $pad_counts,
			'hierarchical' => $hierarchical,
			'title_li'     => $title,
			'hide_empty'   => $empty
	);
	$all_categories = get_categories( $args );
	foreach ($all_categories as $cat) {
		if($cat->category_parent == 0) {
			$category_id = $cat->term_id;       
			#echo '<br /><a href="'. get_term_link($cat->slug, 'product_cat') .'">'. $cat->name .'</a>';
			#We do not want to show the main categories here.

			$args2 = array(
					'taxonomy'     => $taxonomy,
					'child_of'     => 0,
					'parent'       => $category_id,
					'orderby'      => $orderby,
					'show_count'   => $show_count,
					'pad_counts'   => $pad_counts,
					'hierarchical' => $hierarchical,
					'title_li'     => $title,
					'hide_empty'   => $empty
			);
			$sub_cats = get_categories( $args2 );
				if($sub_cats) {
					$val = 0;
					foreach($sub_cats as $sub_category) {
						if($val == 0) {
							echo  '<br/><a class="btn btn-primary btn-lg active px-2" role="button" aria-pressed="true" href="'. get_term_link($sub_category->slug, 'product_cat') .'">'. $sub_category->name .'</a>';
							$val = 1;
						}
						else
						{
							echo  '<br/><a class="btn btn-secondary btn-lg active px-2" role="button" aria-pressed="true" href="'. get_term_link($sub_category->slug, 'product_cat') .'">'. $sub_category->name .'</a>';
							$val = 0;
						}
						
					}
				}
		}       
	}

	
	?>
</div>
<div class="pb-3 pt-3">
	<h6 class="text-center text-grey-border">This site has been originally written in English. All other translations are automatically generated by Google Translate.</h6>
</div>

	</main><!-- #main -->

	<script>
		//image urls - using free images from pexels but hosted to imgur so they should stay alive :). 
        const imageUrls = [
            'https://i.imgur.com/lQXiH4j.jpeg',
            'https://i.imgur.com/AnBmyO3.jpeg',
            'https://i.imgur.com/uqMkqKy.jpeg',
            'https://i.imgur.com/LFHxxaT.jpeg',
            'https://i.imgur.com/YOKNdz6.jpeg',
            'https://i.imgur.com/CxpAPt0.jpeg',
            'https://i.imgur.com/D1VCcni.jpeg',
            'https://i.imgur.com/aqryi6f.jpeg',
            'https://i.imgur.com/GgfnlvF.jpeg',
            'https://i.imgur.com/B18kdhb.jpeg',
            'https://i.imgur.com/uqaJT41.jpeg',
            'https://i.imgur.com/kYTMWof.jpeg'
        ];

        // Function to set one of these images as BG
        function setRandomBackgroundImage() {
            const randomIndex = Math.floor(Math.random() * imageUrls.length);
            const selectedImageUrl = imageUrls[randomIndex];
            document.querySelector('.banner').style.backgroundImage = `url('${selectedImageUrl}')`;
        }

        // Call the function on page load
        window.onload = setRandomBackgroundImage;
    </script>

<?php
get_sidebar();
get_footer();